### ISSUE TITLE
Request: Add git release tags to git repository

### ISSUE THREAD

**Issue by danowar2k** [rschrenk/moodle-filter_h5p#6]
Our deployment mainly uses the git repository. So we would greatly appreciate it if you added git release tags for your versions you released on https://moodle.org/plugins/filter_h5p/versions.

To make it as easy as possible here are the commands that should create the appropriate release tags:

```
# add tag for 1.1 (https://moodle.org/plugins/filter_h5p/1.1-build-2019062500/19842)
git tag -a "1.1" a73870d746185a7e395af0ac50877cf877c7eef5 -m "ADDITIONAL OPTIONAL INFO"
# add tag for 1.2 (https://moodle.org/plugins/filter_h5p/1.2-build-2020061100/21658)
git tag -a "1.2" f23dbfcd8713ff8f19a16a1a7f10c60fe426f1ef -m "ADDITIONAL OPTIONAL INFO"
```

**Comment by rschrenk** [comment]
Hello,
we plan to move towards tagging regarding the specification of Moodle HQ
https://github.com/moodlehq/moodle-plugin-release
Kind regards

**Comment by danowar2k** [comment]
Nice! Looks like a standardization I'll really like :-)
